"use client";
import Image from "next/image";
import { useState } from "react";

type Gallery = { title:string; eyebrow:string; description:string; images:string[] };
const sections: Gallery[] = [
 {eyebrow:"ΓΑΜΟΣ",title:"Ταμπέλα Προετοιμασίας Ζευγαριού",description:"Προσωποποιημένες ταμπέλες για την προετοιμασία του ζευγαριού, σχεδιασμένες αποκλειστικά για τη δική σας ημέρα.",images:["/images/wedding/signs/sign-1.jpeg","/images/wedding/signs/sign-2.jpeg","/images/wedding/signs/sign-3.jpeg","/images/wedding/signs/sign-4.jpeg"]},
 {eyebrow:"ΓΑΜΟΣ",title:"Αρίθμηση Τραπεζιών",description:"Μοναδική αρίθμηση τραπεζιών που προσαρμόζεται στη θεματολογία, στα χρώματα και στις προσωπικές σας λεπτομέρειες.",images:["/images/wedding/tables/table-1.jpeg","/images/wedding/tables/table-2.jpeg","/images/wedding/tables/table-3.jpeg","/images/wedding/tables/table-4.jpeg","/images/wedding/tables/table-5.jpeg","/images/wedding/tables/table-6.jpeg"]},
 {eyebrow:"BACHELORETTE",title:"Δώρα",description:"Προσωποποιημένα αναμνηστικά για την παρέα, με προσεγμένη συσκευασία και σχεδιασμό που ακολουθεί το ύφος της εκδήλωσης.",images:["/images/bachelorette/gifts/gift-1.jpeg","/images/bachelorette/gifts/gift-2.jpeg","/images/bachelorette/gifts/gift-3.jpeg","/images/bachelorette/gifts/gift-4.jpeg"]}
];
export default function Home(){
 const [menu,setMenu]=useState(false); const [lightbox,setLightbox]=useState<string|null>(null);
 return <main>
  <header className="nav"><a href="#top" className="wordmark">amarigio</a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Άνοιγμα μενού">{menu?"×":"☰"}</button><nav className={menu?"open":""}><a href="#wedding" onClick={()=>setMenu(false)}>Γάμος</a><a href="#bachelorette" onClick={()=>setMenu(false)}>Bachelorette</a><a href="#about" onClick={()=>setMenu(false)}>Σχετικά</a><a className="outline" href="https://www.instagram.com/amarigio__/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></nav></header>
  <section className="hero" id="top"><div className="heroText"><p className="eyebrow">PERSONALISED CREATIONS</p><h1>Για τις στιγμές<br/>που είναι <em>μόνο δικές σας.</em></h1><p>Δημιουργίες για γάμους, bachelorette και ξεχωριστές περιστάσεις, σχεδιασμένες με φροντίδα και προσωπικό χαρακτήρα.</p><div className="heroButtons"><a className="button" href="#portfolio">Δείτε τις δημιουργίες</a><a className="textLink" href="https://www.instagram.com/amarigio__/" target="_blank" rel="noopener noreferrer">Μιλήστε μας στο Instagram →</a></div></div><div className="heroLogo"><Image src="/brand/amarigio-logo.png" alt="amarigio" fill priority sizes="(max-width: 800px) 90vw, 45vw"/></div></section>
  <section className="intro" id="about"><p className="eyebrow">AMARIGIO</p><h2>Thoughtfully designed.<br/><em>Beautifully personal.</em></h2><p>Κάθε δημιουργία ξεκινά από τη δική σας ιδέα. Χωρίς έτοιμες λύσεις και χωρίς μαζική παραγωγή. Μόνο λεπτομέρειες που σχεδιάζονται για εσάς και τη στιγμή που θέλετε να κρατήσετε.</p></section>
  <section id="portfolio" className="portfolio">{sections.map((section,index)=><article className="collection" id={index===0?"wedding":index===2?"bachelorette":undefined} key={section.title}><div className="collectionHead"><div><p className="eyebrow">{section.eyebrow}</p><h2>{section.title}</h2></div><p>{section.description}</p></div><div className={`gallery gallery-${section.images.length}`}>{section.images.map((src,i)=><button className="photo" key={src} onClick={()=>setLightbox(src)} aria-label={`Άνοιγμα φωτογραφίας ${i+1} από ${section.title}`}><Image src={src} alt={`${section.title} - φωτογραφία ${i+1}`} fill sizes="(max-width: 700px) 100vw, 33vw"/></button>)}</div></article>)}</section>
  <section className="process"><p className="eyebrow">Η ΔΙΑΔΙΚΑΣΙΑ</p><h2>Από την ιδέα στη δημιουργία.</h2><div className="steps"><div><span>01</span><h3>Μοιράζεστε την ιδέα</h3><p>Μας λέτε την περίσταση, το ύφος και όσα έχετε φανταστεί.</p></div><div><span>02</span><h3>Σχεδιάζουμε για εσάς</h3><p>Διαμορφώνουμε χρώματα, κείμενα και λεπτομέρειες με προσωπικό χαρακτήρα.</p></div><div><span>03</span><h3>Δημιουργούμε</h3><p>Η παραγγελία σας ετοιμάζεται με φροντίδα, αποκλειστικά για τη στιγμή σας.</p></div></div></section>
  <section className="contact"><p className="eyebrow">ΑΣ ΔΗΜΙΟΥΡΓΗΣΟΥΜΕ ΜΑΖΙ</p><h2>Έχετε μια ιδέα;<br/><em>Θέλουμε να την ακούσουμε.</em></h2><p>Στείλτε μας μήνυμα στο Instagram και πείτε μας τι έχετε φανταστεί.</p><a className="button" href="https://www.instagram.com/amarigio__/" target="_blank" rel="noopener noreferrer">@amarigio__ στο Instagram ↗</a></section>
  <footer><span className="wordmark">amarigio</span><p>Personalised creations • Made in Greece</p><p>© {new Date().getFullYear()} amarigio</p></footer>
  {lightbox&&<div className="lightbox" role="dialog" aria-modal="true" onClick={()=>setLightbox(null)}><button onClick={()=>setLightbox(null)} aria-label="Κλείσιμο">×</button><div className="lightboxImage"><Image src={lightbox} alt="Μεγέθυνση δημιουργίας amarigio" fill sizes="95vw"/></div></div>}
 </main>
}
